### ISSUE TITLE
script doesn`t work

### ISSUE THREAD

**Issue by SunSayIsCool** [RoEdAl/al-net-tools#1]
I'm trying to start usb-gadget.sh on raspberry pi zero (archlinux) and it show the "./usb-gadget.sh: line 102: echo: write error: No such device". 
How can I fix it?

**Comment by RoEdAl** [comment]
Build & install package then run service.

If not, load `libcomposite` kernel module by hand and call this script with `up` parameter.

**Comment by SunSayIsCool** [comment]
After start service alarm print this:

[root@alarmpi usb-gadget]# systemctl status usb-gadget
* usb-gadget.service - USB Gadget
     Loaded: loaded (/usr/lib/systemd/system/usb-gadget.service; enabled; vendor preset: disabled)
     Active: inactive (dead)
  Condition: start condition failed at Sat 2020-03-21 08:05:57 UTC; 2s ago
             `- ConditionDirectoryNotEmpty=/sys/class/udc was not met
       Docs: http://github.com/ev3dev/ev3-systemd
             http://irq5.io/2016/12/22/raspberry-pi-zero-as-multiple-usb-gadgets

Mar 21 08:05:57 alarmpi systemd[1]: Condition check resulted in USB Gadget being skipped.


and after manually start script print this:

[root@alarmpi usb-gadget]# ./usb-gadget.sh up
Setting up gadget...
./usb-gadget.sh: line 102: echo: write error: No such device

**Comment by RoEdAl** [comment]
Did you add `dtoverlay=dwc2` to `/boot/config.txt`?
